version: '3.8'

services:
  app:
    build: .
    container_name: feedback_app
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: feedback_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feedback_db
    ports:
      - "3306:3306"